### ISSUE TITLE
New version behaves not as expected when importing old csv files.

### ISSUE THREAD

**Issue by Teages** [XionUzuki/PCtyx#2]
New version behaves not as expected when importing old csv files.

I am making a new level in Ver.131.02a,But I want to try a new version(Ver.150.3).

So I load a old csv file in this.However it doesn't work well.

In fact,I fell the music is a little slower than chart playing,but in Ver.131.02a,it works well and as expected.

**Comment by XionUzuki** [comment]
I am sorry for late reply. Please check if that csv is not corrupted (Which can happen when the csv is under the progress of writing is interrupted). If not, submit the offending files in Discord DM.
v200 will read certain older CSV version files with all sections intact.

As for the audio not sync with chart, it is more apparent in v131.02a. v150.3 onward use a more accurate audio plugin. If the chart is from v131.02a and music is plays early/late (because v131.02a or below has some delay when starting the song), you have to adjust the starting time again.

I'll keep this open in case these issues are still occurring in v200.

**Comment by Teages** [comment]
It works well now.But now there is some new serious problem.
